services:

  mysql:
  image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airline_db

    ports:
    - "3307:3306"

  booking-service:
    build: ./booking-service
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  payment-service:
    build: ./payment-service
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  ticket-service:
    build: ./ticket-service
    ports:
      - "5002:5002"
    depends_on:
      - mysql